//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineStore.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string About_Us {
            get {
                return ResourceManager.GetString("About Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new product.
        /// </summary>
        public static string Add_new_product {
            get {
                return ResourceManager.GetString("Add new product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string Add_to_cart {
            get {
                return ResourceManager.GetString("Add to cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL PRODUCTS.
        /// </summary>
        public static string ALL_PRODUCTS {
            get {
                return ResourceManager.GetString("ALL PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEST OFFER.
        /// </summary>
        public static string BEST_OFFER {
            get {
                return ResourceManager.GetString("BEST OFFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Procedure.
        /// </summary>
        public static string CheckoutProcedure {
            get {
                return ResourceManager.GetString("CheckoutProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COPYRIGHT.
        /// </summary>
        public static string COPYRIGHT {
            get {
                return ResourceManager.GetString("COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEATURED.
        /// </summary>
        public static string FEATURED {
            get {
                return ResourceManager.GetString("FEATURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH DEALS.
        /// </summary>
        public static string FLASH_DEALS {
            get {
                return ResourceManager.GetString("FLASH DEALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET YOUR BEST PRODUCTS.
        /// </summary>
        public static string GET_YOUR_BEST_PRODUCTS {
            get {
                return ResourceManager.GetString("GET YOUR BEST PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAB LAST MINUTE DEALS.
        /// </summary>
        public static string GRAB_LAST_MINUTE_DEALS {
            get {
                return ResourceManager.GetString("GRAB LAST MINUTE DEALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the terms.
        /// </summary>
        public static string I_agree_to_the_terms {
            get {
                return ResourceManager.GetString("I agree to the terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already have a membership.
        /// </summary>
        public static string I_already_have_a_membership {
            get {
                return ResourceManager.GetString("I already have a membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forgot my password.
        /// </summary>
        public static string I_forgot_my_password {
            get {
                return ResourceManager.GetString("I forgot my password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST MINUTE.
        /// </summary>
        public static string LAST_MINUTE {
            get {
                return ResourceManager.GetString("LAST MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsume dolor sit amet, adipisicing elite. Itaque, corporis nulla aspernatur..
        /// </summary>
        public static string Lorem_ipsume_dolor_sit_amet__adipisicing_elite__Itaque__corporis_nulla_aspernatur_ {
            get {
                return ResourceManager.GetString("Lorem ipsume dolor sit amet, adipisicing elite. Itaque, corporis nulla aspernatur" +
                        ".", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member since.
        /// </summary>
        public static string Member_since {
            get {
                return ResourceManager.GetString("Member since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW ARRIVALS ON SALE.
        /// </summary>
        public static string NEW_ARRIVALS_ON_SALE {
            get {
                return ResourceManager.GetString("NEW ARRIVALS ON SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Products.
        /// </summary>
        public static string Our_Products {
            get {
                return ResourceManager.GetString("Our Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Now.
        /// </summary>
        public static string Pay_Now {
            get {
                return ResourceManager.GetString("Pay Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNmuber.
        /// </summary>
        public static string PhoneNmuber {
            get {
                return ResourceManager.GetString("PhoneNmuber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure To Checkout.
        /// </summary>
        public static string Procedure_To_Checkout {
            get {
                return ResourceManager.GetString("Procedure To Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new membership.
        /// </summary>
        public static string Register_a_new_membership {
            get {
                return ResourceManager.GetString("Register a new membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string Remember_Me {
            get {
                return ResourceManager.GetString("Remember Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to start your session.
        /// </summary>
        public static string Sign_in_to_start_your_session {
            get {
                return ResourceManager.GetString("Sign in to start your session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Sign_out {
            get {
                return ResourceManager.GetString("Sign out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bill.
        /// </summary>
        public static string Total_Bill {
            get {
                return ResourceManager.GetString("Total Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Product.
        /// </summary>
        public static string Update_Product {
            get {
                return ResourceManager.GetString("Update Product", resourceCulture);
            }
        }
    }
}
